version: '3.4'

services:
  dockereval:
    image: dockereval
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./config/apache.conf:/etc/apache2/sites-available/apache.conf
      - ./config/script.sh:/script.sh
      - ./joomla-logs/apache/:/var/log/apache2/
    ports:
      - 8000:80
  mysql:
      image: mysql:5.7.22
      command: bash -c "chmod -R 7777 /var/log && chmod 0444 /etc/mysql/my.cnf && service mysql restart && tail -f"
      #command: bash -c "mysqld --user=root --general-log=1 --general-log-file=/var/log/mysql/general-log.log && chmod -R 777 /var/log/mysql/"
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: example
        MYSQL_USER: example
        MYSQL_PASSWORD: example
      ports:
        - 8001:3306
      volumes:
        - ./mysql:/var/lib/mysql
        #- ./config/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        - ./config/my.cnf:/etc/mysql/my.cnf
        - ./joomla-logs/mysql/:/var/log/mysql/
  
